name: Windows RDP Stable

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: System Info
        run: systeminfo

      - name: Install Tailscale
        shell: powershell
        run: |
          choco install tailscale -y
          Start-Sleep -Seconds 15

      - name: Connect Tailscale
        shell: powershell
        run: |
          $ts = "C:\Program Files\Tailscale\tailscale.exe"
          if (!(Test-Path $ts)) {
            $ts = "C:\ProgramData\chocolatey\bin\tailscale.exe"
          }

          & $ts version
          & $ts up --authkey "${{ secrets.TAILSCALE_AUTHKEY }}" --hostname github-rdp

      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create Admin User
        run: |
          net user CloudUser Pass@123456 /add
          net localgroup administrators CloudUser /add

      - name: Show Login Info
        shell: powershell
        run: |
          $ts = "C:\Program Files\Tailscale\tailscale.exe"
          if (!(Test-Path $ts)) {
            $ts = "C:\ProgramData\chocolatey\bin\tailscale.exe"
          }

          Write-Host "================================="
          Write-Host "IP ADDRESS:"
          & $ts ip -4
          Write-Host ""
          Write-Host "USERNAME: CloudUser"
          Write-Host "PASSWORD: Pass@123456"
          Write-Host "================================="

      - name: Keep Alive
        shell: powershell
        run: |
          Start-Sleep -Seconds 21600
